name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release archives
        run: |
          mkdir -p dist/pymon

          cp -r pymon dist/pymon/
          cp README.md LICENSE requirements.txt dist/pymon/

          find dist -type d -name "__pycache__" -exec rm -rf {} +

          cd dist
          tar -czf pymon.tar.gz pymon
          zip -r pymon.zip pymon

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/pymon.tar.gz
            dist/pymon.zip
